# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
defaults: &defaults
  adapter: mysql
  username: work_report
  password: work_report

development:
  <<: *defaults
  database: work_report_blog_development

test:
  <<: *defaults
  database: work_report_blog_test
